services:
  mysql:
    image: mysql:8.0
    container_name: secure_exam_mysql
    environment:
      MYSQL_ROOT_PASSWORD: dakshana2005
      MYSQL_DATABASE: secure_exam_portal
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pdakshana2005"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
